name = "Grumps"
uuid = "3967666a-e078-4e4b-aee9-ca7b8401761d"
authors = ["Joris Pinkse <pinkse@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
